[apple]
chat_db_path = "~/Library/Messages/chat.db"
attachments_path = "~/Library/Messages/Attachments"
permissions_check = true

[monitoring]
poll_interval_seconds = 3
startup_lookback_hours = 24
max_batch_size = 100
enable_real_time = true

[contact-filter]
outbound_behavior = "none" # "whitelist" | "blacklist" | "none"
outbound_ids = []
inbound_behavior = "none" # "whitelist" | "blacklist" | "none"
inbound_ids = []

[date_range]
# start_date = "2024-01-01T00:00:00"
# end_date = "2024-12-31T23:59:59"

[outbound]
method = "applescript"
rate_limit_per_minute = 30