[apple]
chat_db_path = "~/Library/Messages/chat.db"
attachments_path = "~/Library/Messages/Attachments"
permissions_check = true

[monitoring]
poll_interval_seconds = 20 # Used as backup if enable_real_time=true
max_batch_size = 1000
enable_real_time = true

[contacts]
outbound_behavior = "blacklist" # "whitelist" | "blacklist" | "none"
outbound_ids = ["19796656972"]
inbound_behavior = "none" # "whitelist" | "blacklist" | "none"
inbound_ids = []

[date_range] # Ignored when monitoring
# start_date = "2024-01-01T00:00:00"
# end_date = "2024-12-31T23:59:59"
